"""create feedbacks table

Revision ID: 11a11a56db01
Revises: 6a6810254e75
Create Date: 2025-08-28 16:14:58.643300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11a11a56db01'
down_revision: Union[str, None] = '6a6810254e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('subscribe', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.alter_column('shares', 'share_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shares', 'share_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_feedbacks_name'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
