"""create future_votes table

Revision ID: 17b733ab7d81
Revises: ad1bf397906e
Create Date: 2025-08-29 13:57:44.795668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b733ab7d81'
down_revision: Union[str, None] = 'ad1bf397906e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('future_id', sa.Integer(), nullable=False),
    sa.Column('uniq_user_hash', sa.String(length=256), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.String(length=36), nullable=False),
    sa.CheckConstraint('vote BETWEEN 0 AND 3', name='check_vote_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_votes_future_id'), 'future_votes', ['future_id'], unique=False)
    op.create_index(op.f('ix_future_votes_id'), 'future_votes', ['id'], unique=False)
    op.create_index(op.f('ix_future_votes_uniq_user_hash'), 'future_votes', ['uniq_user_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_future_votes_uniq_user_hash'), table_name='future_votes')
    op.drop_index(op.f('ix_future_votes_id'), table_name='future_votes')
    op.drop_index(op.f('ix_future_votes_future_id'), table_name='future_votes')
    op.drop_table('future_votes')
    # ### end Alembic commands ###
