"""create user_prices_table

Revision ID: 756191511eb4
Revises: 8ce849125cd4
Create Date: 2025-09-01 07:20:02.168651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756191511eb4'
down_revision: Union[str, None] = '8ce849125cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniq_user_hash', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_prices_id'), 'user_prices', ['id'], unique=False)
    op.create_index(op.f('ix_user_prices_uniq_user_hash'), 'user_prices', ['uniq_user_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_prices_uniq_user_hash'), table_name='user_prices')
    op.drop_index(op.f('ix_user_prices_id'), table_name='user_prices')
    op.drop_table('user_prices')
    # ### end Alembic commands ###
