"""add is_active column to futures table

Revision ID: 8ce849125cd4
Revises: 17b733ab7d81
Create Date: 2025-09-01 06:58:06.066222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce849125cd4'
down_revision: Union[str, None] = '17b733ab7d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('futures', sa.Column('is_active', sa.Boolean(), nullable=False))
    a=1
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('futures', 'is_active')
    # ### end Alembic commands ###
