"""add uniq_user_hash to feedback

Revision ID: 9238d068d37f
Revises: 756191511eb4
Create Date: 2025-09-01 09:33:51.114173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9238d068d37f'
down_revision: Union[str, None] = '756191511eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('uniq_user_hash', sa.String(length=256), nullable=False))
    op.create_index(op.f('ix_feedbacks_uniq_user_hash'), 'feedbacks', ['uniq_user_hash'], unique=False)
    op.drop_index(op.f('ix_futures_slug'), table_name='futures')
    op.create_index(op.f('ix_futures_slug'), 'futures', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_futures_slug'), table_name='futures')
    op.create_index(op.f('ix_futures_slug'), 'futures', ['slug'], unique=True)
    op.drop_index(op.f('ix_feedbacks_uniq_user_hash'), table_name='feedbacks')
    op.drop_column('feedbacks', 'uniq_user_hash')
    # ### end Alembic commands ###
