"""create futures table

Revision ID: a4ecbe997a27
Revises: 11a11a56db01
Create Date: 2025-08-29 07:58:19.964743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ecbe997a27'
down_revision: Union[str, None] = '11a11a56db01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=256), nullable=True),
    sa.Column('icon_path', sa.String(length=256), nullable=True),
    sa.Column('deadline_year', sa.Integer(), nullable=False),
    sa.Column('deadline_quarter', sa.Integer(), nullable=False),
    sa.CheckConstraint('deadline_quarter BETWEEN 1 AND 4', name='check_quarter_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_futures_id'), 'futures', ['id'], unique=False)
    op.create_index(op.f('ix_futures_slug'), 'futures', ['slug'], unique=True)

    op.add_column('futures', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_name'), table_name='feedbacks')
    op.drop_index(op.f('ix_futures_slug'), table_name='futures')
    op.drop_index(op.f('ix_futures_id'), table_name='futures')
    op.drop_table('futures')
    # ### end Alembic commands ###
