services:
  backend:
    build:
      context: ..
      dockerfile: env/Dockerfile
    volumes:
      - ../app:/app
      - .:/env
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy
    networks:
      - back_net
    depends_on:
      - redis

  mysql:
    image: mysql:8.3
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back_net
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"  # если нужно подключаться с хоста
    networks:
      - back_net
    restart: always

volumes:
  mysql_data:

networks:
  back_net: {}
